name: Python format

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        if: hashFiles('requirements-dev.txt') != ''
        run: pip install -r requirements-dev.txt
      - name: Check format with black
        run: black . --check --diff
