name: Composer

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    paths:
      - "composer.json"
      - "composer.lock"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0]
        composer-version: [1, 2]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          version: ${{ matrix.composer-version }}
          php_extensions: curl iconv intl json ldap
