name: PHP format

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.php"

jobs:
  ecs:
    name: Easy coding standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          version: 2
          php_extensions: curl json
      - name: Run easy coding standard
        run: vendor/bin/ecs check
