name: Python

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        if: hashFiles('requirements-dev.txt') != ''
        run: pip install -r requirements-dev.txt
      - name: Test with unittest
        if: hashFiles('tests/**.py') != ''
        run: python -m unittest
